[versions]
smithy = "1.67.0"
release-plugin = "3.1.0"

[libraries]
smithy-model = { module = "software.amazon.smithy:smithy-model", version.ref = "smithy" }
smithy-openapi = { module = "software.amazon.smithy:smithy-openapi", version.ref = "smithy" }

[bundles]
# Define bundles/groups of libraries

[plugins]
release-plugin = { id = "net.researchgate.release", version.ref = "release-plugin"}
